export const Get_USERS = 'GET_USERS';
export const NEW_USER = 'NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER= 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const DELETE_USER = 'DELETE_USER';
export const NEW_MANGA= 'NEW_MANGA';
export const UPDATE_MANGA = 'UPDATE_MANGA';
export const DELETE_MANGA = 'DELETE_MANGA';
export const SEARCH_MANGA = 'SEARCH_MANGA';
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const GET_MANGA = 'GET_MANGA';
export const GET_GENRES = 'GET_GENRES';
export const GET_AUTH_USER="GET_AUTH_USER"
